### ISSUE TITLE
Translation fixes and finished italian translation

### ISSUE THREAD

**Issue by Rinnegatamante** [nop90/ZeldaOLB#1]
Thanks for this awesome port, i took inspiration from your code refactor in order to port this game to PSVITA.

When working on the port i fixed some typo in the translations, translated some stuffs that weren't already translated (like the Records page/descriptions) and i finished the Italian translation too.

If you want, feel free to use them: https://github.com/Rinnegatamante/ZeldaOLB

I can make a PR too if it would be more suitable for you.

**Comment by nop90** [comment]
Thank you,

If it's easy for you to make a PR it would be better because I'm busy with work now. But if you are busy too, I can merge your changes later when I'll have time. There is no hurry.

Unluckily my Vita is at an unhackable FW, so I can't test your port. I hope that a 2.62 hack will be availabe sooner or later so I can try som coding on Vita too.

**Comment by Rinnegatamante** [comment]
2.62? You can manually update to 3.60 using a DNS trick and setup HENkaku if so.

**Comment by nop90** [comment]
Sorry, typo. I'm on 3.62. :-(

**Comment by nop90** [comment]
PR merged. Now I'm fixing small thing before releasing it.

Thanks again
